config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to:"memos#index"
  get "/new", to:"memos#new"
  post "/create", to:"memos#create"
  get "/memos/:id", to:"memos#destroy"
  get "/memos/:id/edit", to:"memos#edit"
  post "/memos/:id", to:"memos#update"
  get "/categories/:id", to:"categories#show"
  get "/categories/:id/delete", to:"categories#destroy"
  get "/categories/:id/edit", to:"categories#edit"
  post "/categories/:id", to:"categories#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :memos, dependent: :destroy
end

app/models/memo.rb
class Memo < ApplicationRecord
    belongs_to :category
    validates :title, :body, :category_id, presence: true
    validates_uniqueness_of :body && :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :get_category

    def get_category
        @category = Category.all
    end
    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def show
        @categories = Category.find(params[:id])
        @memos = Memo.where(category_id:params[:id])
    end

    def destroy
        memo = Memo.find(params[:id])
        memo.destroy
        redirect_to controller: :categories, action: :show, id: memo.category_id
    end
    
    def edit
        @memo = Memo.find(params[:id])
    end

    def update
        memo = Memo.find(params[:id])
        memo.title = params[:title]
        memo.body = params[:body]
        memo.category_id = params[:select_id]
        if memo.save
            redirect_to controller: :categories, action: :show, id: memo.category_id
        end
    end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
    def index
        @memos = Memo.all
    end

    def new

    end

    def create
        memo = Memo.new(title:params[:title], body:params[:body], category_id:params[:id])
        if memo.save
            redirect_to root_path
        else
            redirect_to new_path
        end
    end
    
    def destroy
        memo = Memo.find(params[:id])
        memo.destroy
        redirect_to root_path
    end
    
    def edit
        @memo = Memo.find(params[:id])
    end
    
    def update
        memo = Memo.find(params[:id])
        memo.title = params[:title]
        memo.body = params[:body]
        memo.category_id = params[:select_id]
        if memo.save
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/categories/edit.html.erb
<div class="mb-3 mt-3">
    <h1>Edit Page</h1>
</div>

<%= form_with url: "/categories/" + @memo.id.to_s do |form| %>
    <div class="mb-3">
        <%= form.label :Title, for: "exampleFormControlInput1", class: "form-label" %>
        <%= form.text_field :title, class: "form-control", id: "exampleFormControlInput1", placeholder: "Title", value: @memo.title %>
    </div>
    <div class="mb-3">
        <%= form.label :Content, for: "exampleFormControlInput2", class: "form-label" %>
        <%= form.text_field :body, class: "form-control", id: "exampleFormControlInput2", placeholder: "Content", value: @memo.body %>
    </div>
    <div class="mb-3">
        <%= form.label :Category, for: "exampleFormControlInput3", class: "form-label"  %>
        <%= form.select :select_id, ["選択してください", ["work", 1], ["life", 2], ["hobby", 3], ["other", 4]], {include_blank: false, selected: "選択してください"}, {id: "exampleFormControlInput3", class: "form-select"} %>
    </div>
    <%= form.submit :submit, class: "btn btn-primary" %>
<% end %>

app/views/categories/show.html.erb
<div class="mb-3 mt-3">
    <h1><%= @categories.name %>'s memo</h1>
</div>

<div class="row">
    <% @memos.each do |memo|%>
        <div class="col-md-4">
            <div class="mb-4">
                <div class="list-group">
                    <div class="list-group-item list-group-item-primary">
                        <h5><%= memo.title %></h5>
                        <p><%= memo.category.name %></p>
                    </div>
                    <div class="list-group-item list-group-item-default">
                        <%= memo.body %>
                        <a href="/categories/<%= memo.id %>/delete">削除</a>
                        <a href="/categories/<%= memo.id %>/edit">編集</a>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Memo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/new">New memo</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Category
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% @category.each do |category| %>
                  <li><a class="dropdown-item" href="/categories/<%= category.id %>"><%= category.name %></a></li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/memos/edit.html.erb
<div class="mb-3 mt-3">
    <h1>Edit Page</h1>
</div>

<%= form_with url: "/memos/" + @memo.id.to_s do |form| %>
    <div class="mb-3">
        <%= form.label :Title, for: "exampleFormControlInput1", class: "form-label" %>
        <%= form.text_field :title, class: "form-control", id: "exampleFormControlInput1", placeholder: "Title", value: @memo.title %>
    </div>
    <div class="mb-3">
        <%= form.label :Content, for: "exampleFormControlInput2", class: "form-label" %>
        <%= form.text_field :body, class: "form-control", id: "exampleFormControlInput2", placeholder: "Content", value: @memo.body %>
    </div>
    <div class="mb-3">
        <%= form.label :Category, for: "exampleFormControlInput3", class: "form-label"  %>
        <%= form.select :select_id, ["選択してください", ["work", 1], ["life", 2], ["hobby", 3], ["other", 4]], {include_blank: false, selected: "選択してください"}, {id: "exampleFormControlInput3", class: "form-select"} %>
    </div>
    <%= form.submit :submit, class: "btn btn-primary" %>
<% end %>

app/views/memos/index.html.erb
<div class="mb-3 mt-3">
    <h1>Memo</h1>
</div>

<div class="row">
    <% @memos.each do |memo|%>
        <div class="col-md-4">
            <div class="mb-4">
                <div class="list-group">
                    <div class="list-group-item list-group-item-primary">
                        <h5><%= memo.title %></h5>
                        <p><%= memo.category.name %></p>
                    </div>
                    <div class="list-group-item list-group-item-default">
                        <%= memo.body %>
                        <a href="memos/<%= memo.id %>">削除</a>
                        <a href="memos/<%= memo.id %>/edit">編集</a>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/memos/new.html.erb
<div class="mb-3 mt-3">
    <h1>New Page</h1>
</div>

<%= form_with url: create_path do |form| %>
    <div class="mb-3">
        <%= form.label :Title, for: "exampleFormControlInput1", class: "form-label" %>
        <%= form.text_field :title, class: "form-control", id: "exampleFormControlInput1", placeholder: "Title", autocomplete: "on" %>
    </div>
    <div class="mb-3">
        <%= form.label :Content, for: "exampleFormControlInput2", class: "form-label" %>
        <%= form.text_field :body, class: "form-control", id: "exampleFormControlInput2", placeholder: "Content", autocomplete: "off" %>
    </div>
    <div class="mb-3">
        <%= form.label :Category, for: "exampleFormControlInput3", class: "form-label"  %>
        <%= form.select :id, ["選択してください", ["work", 1], ["life", 2], ["hobby", 3], ["other", 4]], {include_blank: false, selected: "選択してください"}, {id: "exampleFormControlInput3", class: "form-select"} %>
    </div>
    <%= form.submit :保存, class: "btn btn-primary" %>
<% end %>